version: '3'
services:
  backendtest:
    build: .
    ports:
     - "8080:8080"
    depends_on:
     - mysql
  mysql:
    image: "mysql/mysql-server:5.7"
    ports:
     - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5