version: '3'
services:
  backendtest:
    build: .
    ports:
     - "8080:8080"
  mysql:
    image: "mysql/mysql-server:5.7"
    environment:
    - MYSQL_ROOT_HOST="127.*.0.1"
    - MYSQL_ROOT_PASSWORD="example"
    ports:
     - "3306:3306"
